[workspace]
members = ["calculator", "calculator_cli", "calculator_web"]
resolver = "2"

[workspace.package]
authors = ["Nico"]
edition = "2021"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.75"
thiserror = "1.0.50"

[profile.release]
lto = true
