[package]
name = "calculator"
version = "0.1.0"
description = "library package for the `calculator` project."
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror = { workspace = true }
